// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaennSqIMUqWt7BDEIISKSWtYgC_X3ya0',
    appId: '1:684302097214:android:2d64f57015eb5185b16a6f',
    messagingSenderId: '684302097214',
    projectId: 'weather-service-1a272',
    databaseURL: 'https://weather-service-1a272-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'weather-service-1a272.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_dcBOnYYK0uwoJfGohlZ1m_3j0pTYKns',
    appId: '1:684302097214:ios:cec89e3d5d3021b3b16a6f',
    messagingSenderId: '684302097214',
    projectId: 'weather-service-1a272',
    databaseURL: 'https://weather-service-1a272-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'weather-service-1a272.appspot.com',
    iosClientId: '684302097214-5h9b5ofepphlc4ss1umovc9pdjononuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherService',
  );
}
